### ISSUE TITLE
Add 'Second Brain URL' field to tribe settings

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1542]
**Task**

Add a `Second Brain URL` field to tribe settings:

This is the current Apps UI example of current fields:
![Image](https://github.com/stakwork/sphinx-tribes/assets/142233216/62e189f6-733e-4ca9-a480-03af15c0a538)

- We need a new field called SecondBrain URL for tribe settings

**Acceptance Criteria**

- [ ] A new column field for SecondBrain url

**Comment by tomsmith8** [comment]
- [ ] Need to sync with Relay
- [ ] Need to update client apps

**Comment by gouravmpk** [comment]
@tomsmith8  assign
