### ISSUE TITLE
Parent Issue Tracking

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1898]
Issues:

- [ ] Failed Payments being recorded on workspace trxn history
- [ ] Paying multiple failed bounties being recorded on workspace trxn list
- [ ] Failed payments - Payment bot is too [Liquidity]
- [ ] Workspace balances and details exposed on API (need to check the which endpoint /workspace)
- [ ] Ability to edit, delete assignee and bounty after completed and sending async payment 
- [ ] Admin View and Workspace History are inconsistent

**Comment by tomsmith8** [comment]
Tracking Payment issues here that have happened post v2 migration and trying to make payments

**Comment by tomsmith8** [comment]
Fixes so far to be tested:

- [ ] A user cannot update a bounty when a bounty is pending
- [ ] Only pending and completed payments affects the bounty budgets and are seen on the payment history
- [ ] Payment Status are not checked for failed payments
