### ISSUE TITLE
Implement Workflow Database Layer

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1937]
### Context
Create database models and operations for workflow requests and processing map.

### Technical Details
- Create models in `/db/workflow_models.go`
- Implement database operations in `/db/workflow_db.go`
- Set up processing map table

### Technical Implementation Details

This includes a new table to map processing logic to utility functions and updates to the wf_requests table to track 

1. Database Models
```go
// db/models/workflow.go
type wf_processing_map struct {
    gorm.Model
    Type              string `gorm:"index"` // "source" or "action"
    ProcessKey        string `gorm:"index"` // the source or action string
    RequiresProcessing bool         // default false
    HandlerFunc       string        // must be present for RequiresProcessing == true
    Config           JSON           // optional for future 
}


//Updates to wf_requests
type wf_requests struct {
    gorm.Model
    requestUUID         string `gorm:"index"` // "source" or "action"
    workflowID          string `gorm:"index"` // the source or action string
    source              string          // where did the request come from
    action              string           // what action do we take on response
    status              string           // current status of the request new | pending | fail | success
    projectID         string           // set on return of OK status from Stakwork. Identifies workflow run.  
    requestData         JSON      
    responseData        JSON
}
```

2. DB operations
```
// db/workflow_db.go
func CreateWorkflowRequest(req *WorkflowRequest) error {
    return db.Create(req).Error
}

func LookupProcessingConfig(procType, key string) (*ProcessingMap, error) {
    var config ProcessingMap
    err := db.Where("type = ? AND process_key = ?", procType, key).First(&config).Error
    return &config, err
}
```

3. Migrations
```
// migrations/xxx_workflow_tables.go
func (m *Migration) Up() {
    // Create tables
    // Add indexes
    // Initial processing map data
}
```

Notes for Implementer

- Consider adding soft deletes
- Add database constraints
- Consider adding audit fields

### Tasks
- [ ] Create WorkflowRequest model
- [ ] Create ProcessingMap model
- [ ] Implement CRUD operations for workflow requests
- [ ] Add database indexes
- [ ] Add model validations
- [ ] Create database tests

### Acceptance Criteria
- [ ] Models correctly defined with GORM tags
- [ ] Database operations working:
  - Create workflow request
  - Lookup processing requirements
  - Update request status
- [ ] Indexes created for performance
- [ ] Integration tests verify database operations
- [ ] Tests pass with >90% coverage

### Dependencies
- None (but required for https://github.com/stakwork/sphinx-tribes/issues/1939)

### Migration Requirements
- [ ] Add indexes on `request_uuid`, `source`, `status`
- [ ] Create `wf_processing_map` table

**Comment by aliraza556** [comment]
U

**Comment by humansinstitute** [comment]
@aliraza556 i think it will work for you to do the extra DB piece here as it aligns to the update you worked on yesterday.
