### ISSUE TITLE
Create Workflow Processing Utilities

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1939]
### Context
Implement utility functions for workflow request processing, including source lookup and processing logic.

### Technical Details
- Create utilities in `/utils/workflow_processor.go`
- Implement processing map lookup logic
- Handle request enrichment and processing

### Technical Implementation Details

1. Main Processing Function
```go
// utils/workflow_processor.go

type ProcessorConfig struct {
    RequiresProcessing bool
    HandlerFunc        string
    Config            json.RawMessage
}

func ProcessWorkflowRequest(request models.WorkflowRequest) (*models.WorkflowResponse, error) {
    // Check processing requirements
    config, err := lookupProcessingConfig(request.Source)
    if err != nil {
        return nil, fmt.Errorf("config lookup failed: %w", err)
    }
    
    // If no processing needed, return early
    if config == nil || !config.RequiresProcessing {
        return handleDefaultFlow(request)
    }
    
    // Process with specific handler
    return processWithHandler(request, config)
}
```

2. Processing Map Lookup

```go
func lookupProcessingConfig(source string) (*ProcessorConfig, error) {
    // Lookup implementation using DB layer
    // Return nil if no processing needed
}

func processWithHandler(request models.WorkflowRequest, config *ProcessorConfig) (*models.WorkflowResponse, error) {
    // Handler lookup and execution
}
```

3. Test Implementation

```go
func TestProcessWorkflowRequest(t *testing.T) {
    // Test different scenarios:
    // - Source requires processing
    // - Source doesn't require processing
    // - Invalid source
    // - Processing errors
}
```

Notes for Implementer

- Consider caching processing map lookups
- Add telemetry for processing duration
- Consider retry logic for transient failures
- Add detailed logging for debugging

### Tasks
- [ ] Create `ProcessWorkflowRequest` function
- [ ] Implement source processing lookup
- [ ] Add UUID generation for requests
- [ ] Create validation utilities
- [ ] Add comprehensive unit tests
- [ ] Implement error handling utilities

### Acceptance Criteria
- [ ] Utility functions handle source processing lookup
- [ ] UUID generation works correctly
- [ ] Processing logic correctly routes based on source lookup
- [ ] Error handling is comprehensive
- [ ] Unit tests cover processing scenarios
- [ ] Tests pass with >90% coverage

### Dependencies
- Workflow DB Layer (#ticket4)

**Comment by humansinstitute** [comment]
Break down of higher level ticket - @MahtabBukhari

**Comment by MirzaHanan** [comment]
@humansinstitute i can help?

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?
