### ISSUE TITLE
Implement Workflow Request Handler

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1940]
### Context
Create handler function to process incoming workflow requests and coordinate between HTTP layer and business logic.

### Technical Details
- Create handler in `/handlers/workflow_handler.go`
- Handle request validation and processing coordination
- Part of workflow request processing implementation (#parent_ticket)

### Technical Implementation Details

1. Handler Structure
```go
// handlers/workflow_handler.go

// Main handler function
func HandleWorkflowRequest(c *gin.Context) {
    var request models.WorkflowRequest
    if err := c.BindJSON(&request); err != nil {
        handleError(c, err)
        return
    }
    
    // Process request using utils
    result, err := utils.ProcessWorkflowRequest(request)
    if err != nil {
        handleError(c, err)
        return
    }
    
    c.JSON(http.StatusOK, gin.H{
        "request_id": result.RequestUUID,
        "status": "success",
    })
}

// Error handling helper
func handleError(c *gin.Context, err error) {
    // Different error types = different status codes
    // Implementation details here
}
```

2. Request Validation
```
// Example validation struct
type WorkflowRequestPayload struct {
    RequestID    string          `json:"request_id" binding:"omitempty,uuid"`
    WorkflowType string          `json:"workflow_type" binding:"required"`
    Source       string          `json:"source" binding:"required"`
    Payload      json.RawMessage `json:"payload" binding:"required"`
}
```
3. Test Cases
```
func TestHandleWorkflowRequest(t *testing.T) {
    tests := []struct {
        name           string
        payload        string
        expectedCode   int
        expectedError  bool
    }{
        {
            name: "valid_request",
            payload: `{"workflow_type":"test","source":"test","payload":{}}`,
            expectedCode: 200,
        },
        // Add more test cases...
    }
    // Implement tests
}
```
Notes for Implementer

- Use existing error handling patterns
- Consider adding request logging
- Add metrics for monitoring
- Consider adding context timeout
- Handle JSON validation carefully

### Tasks
- [ ] Create `HandleWorkflowRequest` function
- [ ] Implement request payload validation
- [ ] Add error handling for common scenarios
- [ ] Implement response formatting
- [ ] Add handler unit tests

### Acceptance Criteria
- [ ] Handler validates incoming JSON payload
- [ ] Handler returns appropriate HTTP status codes:
  - 200: Success with request_id
  - 400: Invalid payload
  - 500: Internal processing errors
- [ ] Handler correctly passes data to utility functions
- [ ] Unit tests cover happy path and error scenarios
- [ ] Tests pass with >90% coverage

### Dependencies
- Workflow Request Route (https://github.com/stakwork/sphinx-tribes/issues/1938)
- Will be used by Workflow Utils (https://github.com/stakwork/sphinx-tribes/issues/1939)

**Comment by saithsab877** [comment]
@humansinstitute Please assign me?

**Comment by Shoaibdev7** [comment]
@humansinstitute assign me?

**Comment by humansinstitute** [comment]
This is a breakdown of work already assigned to @MahtabBukhari

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?
