### ISSUE TITLE
Feature Tracking: Audio Feature Descriptions

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1957]
## Context

This feature will allow us to test the ability to convert an audio recording or conversation into a feature brief. Via a stakwork workflow. 

Background:
Version 1 of this workflow will assume a recording has been made and uploaded to a public URL for inclusion. This can be improved at a later date. 

## Task Breakdown

- [ ] [Simplify the Audio workflow for Feature Descriptions](https://github.com/stakwork/senza-lnd/issues/6626)
- [ ] Update Feature Brief form to generate a workflow request
- [ ] Pop up form with audio URL
- [ ] Post form with data and audio URL to /features/generate
- [ ] Build route /features/generate 
- [ ] Build Handler to send request to Stakwork
- [ ] Build webhook on stakwork to receive data
- [ ] Bild Handler to add to Feature Brief.

**Comment by saithsab877** [comment]
J

**Comment by aliraza556** [comment]
@humansinstitute assign me

**Comment by humansinstitute** [comment]
This is tracking feature, no assignments here.
