### ISSUE TITLE
Feature Tracking: Requirements Generation

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1962]
## Context

This feature will allow us to test the ability to convert an audio recording or conversation into a feature brief. Via a stakwork workflow. 

Background:
Version 1 of this workflow will assume a recording has been made and uploaded to a public URL for inclusion. This can be improved at a later date. 

## Task Breakdown

- [ ] Requirements Generation Workflow
- [ ] Front end to Gather Data and Generate Workflow
- [ ] End Ppoint to acept POst Data and Send to Stakwork
- [ ] End Point to Process and Load Data
