### ISSUE TITLE
Feature Tracking: Phase Planner

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1967]
## Content

Add a feature planner to the Bounties Site to increase throughput of ticket creation by Product Manager. 

This can be envisioned as a new view on the site, access via a button on the Feature > Phase. 

![Image](https://github.com/user-attachments/assets/c7907ddc-b49c-4681-81dc-9d308e011148)

This allows a PM to bulk edit multiple draft tickets supported by AI workflows. 

## Integration Bugs

DB Call not triggering with Object Payload
- [x] stakwork/sphinx-tribes-frontend#679
- [x] stakwork/sphinx-tribes#2022
- [x] stakwork/sphinx-tribes#2024
- [x] stakwork/sphinx-tribes#2026
- [x] stakwork/sphinx-tribes-frontend#684
- [x] stakwork/sphinx-tribes#2030
- [ ] stakwork/sphinx-tribes-frontend#686
- [x] #2033
- [x] #2035

Endpoint Conflict Issue and DB versioning on UUID
- [x] stakwork/sphinx-tribes-frontend#677
- [x] stakwork/sphinx-tribes#2017
- [x] stakwork/sphinx-tribes#2020

Resolved for CORS endpoint issues

- [x] stakwork/sphinx-tribes#2005
- [x] stakwork/sphinx-tribes#2006

## Phase Plan

1. We will need a navigation flow to access the ticket plan
- [x] stakwork/sphinx-tribes-frontend#660

3. We will need a new page to manage creation of ticket plans
- [x] stakwork/sphinx-tribes-frontend#658
    - [x] Retrieve title from endpoint get: /feature/UUID
    - [x] Retrieve Phase title from endpoint get: /phase/UUID
- [x] [Create add ticket button](https://github.com/stakwork/sphinx-tribes-frontend/issues/663)

4. We will need components for the editing of draft tickets
- [x] [create a component 'ticket editor' which displays a text box when added to the screen](https://github.com/stakwork/sphinx-tribes-frontend/issues/664)
    - [x] Update 'ticket editor' component - display title "Ticket {N}" where N = sequence number for phaseUUID
    - [x] Update 'ticket editor' component - with "Update" button with styling and position as per screenshot
- [x] https://github.com/stakwork/sphinx-tribes-frontend/issues/665
- [x] https://github.com/stakwork/sphinx-tribes-frontend/issues/667
- [x] stakwork/sphinx-tribes-frontend#669
- [x] stakwork/sphinx-tribes-frontend#670
- [x] stakwork/sphinx-tribes-frontend#674

5. The data model will need a concept of "tickets"
- [x] stakwork/sphinx-tribes#1971
- [x] stakwork/sphinx-tribes#1976 - (also Create handler for database interaction)
- [x] stakwork/sphinx-tribes#1977
- [x] stakwork/sphinx-tribes#1978
- [x] stakwork/sphinx-tribes#1979

6. The Phase Planner Page will display all current tickets for this phase for editing.

- [x] stakwork/sphinx-tribes#1982
- [x] stakwork/sphinx-tribes#1983
- [x] stakwork/sphinx-tribes#1984

7. Workflows will take shorthand draft tickets and expand the ticket
- [x] https://github.com/stakwork/senza-lnd/issues/6646
    - [x] on "ticket editor" component add button "ticket review"
- [x] stakwork/sphinx-tribes-frontend#671 - (source = text box in ticket editor component)

8. Workflow integration will be processed by Sphinx Tribes Server
- [x] stakwork/sphinx-tribes#1985
- [x] stakwork/sphinx-tribes#1986
- [x] stakwork/sphinx-tribes#1998

9. Workflow response will be processed by Sphinx Tribes and updates server
- [x] stakwork/sphinx-tribes#1988
- [x] stakwork/sphinx-tribes#1999

----- 
**Deprecated**
- [x] stakwork/sphinx-tribes-frontend#659
- [x] stakwork/sphinx-tribes#1972
