### ISSUE TITLE
GET - Tickets by Phase UUID

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1972]
# Ticket Name: Implement GET Endpoint for Phase-Specific Tickets

## Context
As part of the Sphinx Bounties project's ticket management system, we need to implement a new API endpoint to retrieve tickets associated with specific phases. This functionality is essential for:
- Supporting phase-specific ticket visualization in the frontend
- Enabling effective task management within phases
- Facilitating the tracking of work items across the project lifecycle
- Maintaining data consistency between features and their associated phases

## Task
The implementation consists of the following steps:

1. Route Configuration
   - Add new route in `features.go`
   - Configure path parameters for feature and phase UUIDs
   - Connect route to appropriate handler

2. Handler Implementation
   - Create `GetTicketsByPhaseUUID` handler function
   - Implement parameter validation
   - Add database query logic
   - Implement error handling and response formatting

3. Database Integration
   - Implement query to filter tickets by phase UUID
   - Ensure proper joins with related tables if needed
   - Optimize query performance with appropriate indexes

4. Response Handling
   - Implement response serialization based on Ticket struct
   - Add pagination if required
   - Format error responses according to API standards

## Outcome
A production-ready GET endpoint that:
- Retrieves all tickets associated with a specified phase UUID
- Returns data formatted according to the Ticket struct specification
- Handles errors gracefully and provides meaningful error messages
- Performs efficiently at scale

### API Specification
```
Method: GET
Path: /feature/{feature_uuid}/phase/{phase_uuid}/tickets
```

### Parameters
1. Path Parameters:
   - `feature_uuid`: UUID string (required)
   - `phase_uuid`: UUID string (required)

### Response Structure
```go
type Ticket struct {
    UUID        string       `gorm:"primaryKey;type:uuid;default:uuid_generate_v4()"`
    FeatureUUID string       `gorm:"type:uuid;not null;index"`
    PhaseUUID   string       `gorm:"type:uuid;not null;index"`
    Name        string       `gorm:"type:varchar(255);not null"`
    Sequence    int          `gorm:"type:integer;not null"`
    Dependency  []int        `gorm:"type:integer[]"`
    Description string       `gorm:"type:text"`
    Status      TicketStatus `gorm:"type:varchar(50);not null;default:'draft'"`
    CreatedAt   time.Time    `gorm:"type:timestamp;not null;default:current_timestamp"`
    UpdatedAt   time.Time    `gorm:"type:timestamp;not null;default:current_timestamp"`
}
```

### Error Handling
Must handle the following scenarios:
1. Invalid UUID format
2. Non-existent feature/phase
3. Database connection issues
4. Authorization failures
5. Server errors

### Implementation Notes
1. Database Query:
   ```sql
   SELECT * FROM tickets 
   WHERE phase_uuid = $1 
   AND feature_uuid = $2 
   ORDER BY sequence ASC;
   ```

2. Required Indexes:
   - `phase_uuid`
   - `feature_uuid`
   - Combined index on (`phase_uuid`, `feature_uuid`)

### Functional Requirements
- [ ] Endpoint returns correct list of tickets when valid UUIDs are provided
- [ ] Response structure matches the Ticket struct specification
- [ ] Empty result sets return valid JSON array (`[]`)
- [ ] All ticket fields are properly serialized
- [ ] Tickets are ordered by sequence number

### Error Handling
- [ ] Returns 400 for invalid UUID format
- [ ] Returns 404 for non-existent feature/phase
- [ ] Returns 403 for unauthorized access
- [ ] Returns 500 for database/server errors
- [ ] Error responses include appropriate error messages

### Performance
- [ ] Response time under 200ms for up to 1000 tickets
- [ ] Efficient database query execution plan
- [ ] Proper use of database indexes

### Testing Requirements
- [ ] Unit tests for handler function
- [ ] Integration tests for database queries
- [ ] Load testing for performance criteria
- [ ] Error scenario testing
- [ ] Edge case testing (empty results, maximum loads)

### Documentation
- [ ] API documentation updated with new endpoint
- [ ] Example requests and responses documented
- [ ] Error scenarios documented

### Security
- [ ] Authentication middleware properly configured
- [ ] Authorization checks implemented
- [ ] Input validation for all parameters

**Comment by aliraza556** [comment]
U

**Comment by MahtabBukhari** [comment]
e

**Comment by Shoaibdev7** [comment]
@humansinstitute assign me

**Comment by Shoaibdev7** [comment]
@humansinstitute assign me
