### ISSUE TITLE
Create a route to interact with db.ticket at `bounty/ticket/uuid`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1976]
## Context
We need to create a new API endpoint to handle ticket operations (read/update/delete) as part of the bounty system. This ticket focuses on implementing the route endpoint and handler structure, which will interface with utility functions (to be implemented in a separate ticket) for database operations.

## Task
Create a new REST endpoint at `/bounty/ticket/{uuid}` with a handler that processes incoming requests and routes them to the appropriate utility functions.

## Outcome
A functioning API endpoint that can receive and validate requests for ticket operations, with proper request parsing and error handling, ready to be connected to utility functions.

### 1. Request/Response Objects
```go
// Request structure
type TicketRequest struct {
    Action string       `json:"action"`  // "read" | "update" | "delete"
    Ticket types.Ticket `json:"ticket"`
}

// Response structure
type TicketResponse struct {
    Success bool        `json:"success"`
    Data    *Ticket    `json:"data,omitempty"`
    Error   string     `json:"error,omitempty"`
}
```

### 2. Handler Function
```go
func TicketHandler(w http.ResponseWriter, r *http.Request) {
    vars := mux.Vars(r)
    uuid := vars["uuid"]
    
    var req TicketRequest
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        respondWithError(w, http.StatusBadRequest, "Invalid request format")
        return
    }

    switch req.Action {
    case "read":
        handleTicketRead(w, uuid)
    case "update":
        handleTicketUpsert(w, uuid, req.Ticket)
    case "delete":
        handleTicketDelete(w, uuid)
    default:
        respondWithError(w, http.StatusBadRequest, "Invalid action")
    }
}
```

### 3. Action Handler Functions
```go
func handleTicketRead(w http.ResponseWriter, uuid string) {
    ticket, err := utils.GetTicket(uuid)
    if err != nil {
        respondWithError(w, http.StatusNotFound, "Ticket not found")
        return
    }
    respondWithJSON(w, http.StatusOK, TicketResponse{Success: true, Data: ticket})
}

func handleTicketUpsert(w http.ResponseWriter, uuid string, ticket Ticket) {
    ticket.UUID = uuid
    updatedTicket, err := utils.UpsertTicket(ticket)
    if err != nil {
        respondWithError(w, http.StatusInternalServerError, "Failed to upsert ticket")
        return
    }
    respondWithJSON(w, http.StatusOK, TicketResponse{Success: true, Data: updatedTicket})
}

func handleTicketDelete(w http.ResponseWriter, uuid string) {
    if err := utils.DeleteTicket(uuid); err != nil {
        respondWithError(w, http.StatusInternalServerError, "Failed to delete ticket")
        return
    }
    respondWithJSON(w, http.StatusOK, TicketResponse{Success: true})
}
```

### 4. Response Helper Functions
```go
func respondWithError(w http.ResponseWriter, code int, message string) {
    respondWithJSON(w, code, TicketResponse{Success: false, Error: message})
}

func respondWithJSON(w http.ResponseWriter, code int, payload interface{}) {
    response, _ := json.Marshal(payload)
    w.Header().Set("Content-Type", "application/json")
    w.WriteHeader(code)
    w.Write(response)
}
```

## Acceptance Criteria
- [ ] Endpoint `/bounty/ticket/{uuid}` is properly registered in the router
- [ ] Handler correctly parses incoming requests and validates the action type
- [ ] UUID validation is implemented
- [ ] Response helper functions properly format JSON responses
- [ ] Error handling is implemented for request parsing
- [ ] Handler functions are prepared to integrate with utility functions

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?

**Comment by aliraza556** [comment]
@humansinstitute Please assign me
