### ISSUE TITLE
Create util function for to upsert ticket record in database

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1977]
## Context
To support the ticket API endpoint's update operation, we need to implement a database utility function that can both create new tickets and update existing ones.

## Task
Create a utility function that handles both insertion and updating of ticket records using GORM.
Please follow standards and conventions in line with the Bounty platform architecture. 
This will be called via the route at: https://github.com/stakwork/sphinx-tribes/issues/1976

## Outcome
A utility function that can reliably create new tickets or update existing ones based on UUID.

## Design
```go
// utils/ticket.go
package utils

import (
    "fmt"
    "errors"
    "gorm.io/gorm"
)

func UpsertTicket(ticket Ticket) (*Ticket, error) {
    var existingTicket Ticket
    
    result := db.Where("uuid = ?", ticket.UUID).First(&existingTicket)
    
    if result.Error != nil {
        if errors.Is(result.Error, gorm.ErrRecordNotFound) {
            // Create new ticket
            if err := db.Create(&ticket).Error; err != nil {
                return nil, fmt.Errorf("failed to create ticket: %w", err)
            }
            return &ticket, nil
        }
        return nil, fmt.Errorf("database error: %w", result.Error)
    }
    
    // Update existing ticket
    if err := db.Model(&existingTicket).Updates(ticket).Error; err != nil {
        return nil, fmt.Errorf("failed to update ticket: %w", err)
    }
    
    return &ticket, nil
}
```

## Acceptance Criteria
- [ ] Function handles both creation and updates correctly
- [ ] CreatedAt timestamp is set for new tickets
- [ ] UpdatedAt timestamp is updated appropriately
- [ ] Required fields are validated before save
- [ ] Function maintains data integrity for all ticket fields
- [ ] Proper error handling for database operations
- [ ] Unit tests implemented with test cases for:
  - Creating new ticket
  - Updating existing ticket
  - Invalid data scenarios
  - Database errors

**Comment by MuhammadUmer44** [comment]
B

**Comment by MahtabBukhari** [comment]
s
