### ISSUE TITLE
Create util function for to read ticket records from database

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1978]
# Ticket Name: Implement Get Ticket Database Function

## Context
To support the ticket API endpoint's read operation, we need to implement a database utility function that retrieves ticket records by UUID.

## Task
Create a utility function that retrieves ticket records from the database using GORM.
This will interface with Ticket table at: https://github.com/stakwork/sphinx-tribes/issues/1971
and will be called by: https://github.com/stakwork/sphinx-tribes/issues/1976

## Outcome
A utility function that can reliably fetch ticket records by UUID with proper error handling.

## Design
```go
// utils/ticket.go
package utils

import (
    "fmt"
    "gorm.io/gorm"
)

func GetTicket(uuid string) (*Ticket, error) {
    var ticket Ticket
    result := db.Where("uuid = ?", uuid).First(&ticket)
    if result.Error != nil {
        if errors.Is(result.Error, gorm.ErrRecordNotFound) {
            return nil, fmt.Errorf("ticket not found: %w", result.Error)
        }
        return nil, fmt.Errorf("failed to get ticket: %w", result.Error)
    }
    return &ticket, nil
}
```

## Acceptance Criteria
- [ ] Function correctly retrieves ticket data by UUID
- [ ] Proper error handling for non-existent tickets
- [ ] Proper error handling for database errors
- [ ] Function returns complete ticket struct with all fields
- [ ] Unit tests implemented with test cases for: 
  - Successful retrieval
  - Non-existent UUID
  - Invalid UUID format
  - Database connection errors

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by MahtabBukhari** [comment]
r
