### ISSUE TITLE
Create util function for to delete record database

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1979]
## Context
To support the ticket API endpoint's delete operation, we need to implement a database utility function that removes ticket records by UUID.
This will interface with Ticket table at: https://github.com/stakwork/sphinx-tribes/issues/1971
and will be called by: https://github.com/stakwork/sphinx-tribes/issues/1976

## Task
Create a utility function that handles the deletion of ticket records using GORM.

## Outcome
A utility function that can reliably delete ticket records with proper error handling and validation.

## Design
```go
// utils/ticket.go
package utils

import (
    "fmt"
    "gorm.io/gorm"
)

func DeleteTicket(uuid string) error {
    result := db.Where("uuid = ?", uuid).Delete(&Ticket{})
    if result.Error != nil {
        return fmt.Errorf("failed to delete ticket: %w", result.Error)
    }
    if result.RowsAffected == 0 {
        return fmt.Errorf("ticket not found")
    }
    return nil
}
```

## Acceptance Criteria
- [ ] Function correctly deletes ticket by UUID
- [ ] Proper error handling for non-existent tickets
- [ ] Function returns appropriate error for failed deletions
- [ ] Successful deletion returns nil error
- [ ] Unit tests implemented with test cases for:
  - Successful deletion
  - Non-existent UUID
  - Invalid UUID format
  - Database errors

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by MahtabBukhari** [comment]
d
