### ISSUE TITLE
Create Util function to retrieve all tickets in a phase

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1984]
## Context
To support the phase tickets endpoint and maintain separation of concerns, we need a dedicated utility function that handles the database query for retrieving tickets associated with a phase UUID.

Please respect existing conventions and standards in Sphinx Tribes Architecture. 

Will support:
- route: https://github.com/stakwork/sphinx-tribes/issues/1982
- handler: https://github.com/stakwork/sphinx-tribes/issues/1983

## Task
Create a utility function `GetTicketsByPhase` that queries the database and returns an array of ticket objects for a given phase UUID.

## Outcome
A reusable utility function that handles all database operations for retrieving tickets by phase UUID.

## Design
```go
// utils/ticket.go
package utils

import (
    "fmt"
    "gorm.io/gorm"
)

// GetTicketsByPhase retrieves all tickets associated with a phase UUID
func GetTicketsByPhase(phaseUUID string) ([]Ticket, error) {
    var tickets []Ticket
    
    result := db.Where("phase_uuid = ?", phaseUUID).
        Order("sequence ASC").
        Find(&tickets)
    
    if result.Error != nil {
        return nil, fmt.Errorf("failed to fetch tickets for phase: %w", result.Error)
    }
    
    // Return empty slice if no tickets found
    if result.RowsAffected == 0 {
        return []Ticket{}, nil
    }
    
    return tickets, nil
}
```

## Acceptance Criteria
- [ ] Function correctly queries tickets by phase UUID
- [ ] Results are ordered by sequence number
- [ ] Function returns full ticket objects
- [ ] Proper error handling for database errors
- [ ] Empty result handled correctly (returns empty slice, not nil)
- [ ] Unit tests cover:
  - [ ] Successful retrieval
  - [ ] Non-existent phase UUID
  - [ ] Database errors
  - [ ] Empty results
