### ISSUE TITLE
Endpoint for bounty/ticket/review/send

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1985]
## Context
We need an endpoint to handle ticket submissions from our Ticket Builder frontend. 

This endpoint will:
- Receive structured ticket data from the frontend https://github.com/stakwork/sphinx-tribes-frontend/issues/671
- Validate the submission against our data schema
- Return appropriate success/error responses

## Task
1. Create and configure the `/bounty/ticket/review/send` POST endpoint
2. Pass to handler Handler for PostTicketDataToStakwork

## Outcome
Implement route to send data to stakwork as part of ticket builder. 

### Request Schema
```typescript
interface TicketSubmission {
  uuid: string;              // UUID v4 format
  feature_uuid: string;      // UUID v4 format
  phase_uuid: string;        // UUID v4 format
  name: string;              // 3-200 characters
  sequence: number;          // Ticket order in workflow
  dependency: string[];      // Array of ticket UUIDs
  description: string;       // Max 5000 characters
  status: 'DRAFT' | 'REVIEW' | 'APPROVED';
  version: number;
  created_at: Date;
  updated_at: Date;
}
```

### Response Schema
```typescript
interface TicketResponse {
  success: boolean;
  ticket_id: string;
  message: string;
  errors?: string[];
}
```

## Acceptance Criteria
- [ ] Endpoint correctly processes valid ticket submissions
- [ ] Error Handling
  - [ ] Returns appropriate HTTP status codes
  - [ ] Provides clear error messages

**Comment by saithsab877** [comment]
@humansinstitute, Please assign me?

**Comment by Shoaibdev7** [comment]
@humansinstitute, I can help?

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me

**Comment by aliraza556** [comment]
@humansinstitute, Please assign me?
