### ISSUE TITLE
Handler for PostTicketDataToWorkflow

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1986]
# Ticket Name: Implement Handler for PostTicketDataToWorkflow

## Context
The system requires a handler to process ticket information received from a ticket editor component. This handler will be responsible for preparing and sending ticket data to a workflow system. 

This will follow a similar pattern to https://github.com/stakwork/sphinx-tribes/issues/1959

- The end point will receive data from ticket editor component
- Create a workflow send object (see example below)
- Product Brief would be returned from a util function (stub now and use test data from example) 
- Feature Brief will be returned from a util function (stub now and use test data from example)

Please note that the API key is not valid.

```
curl --location 'https://api.stakwork.com/api/v1/projects' \
--header 'Authorization: Token token="aaaaaaahhhhhnoooooo"' \
--header 'Content-Type: application/json' \
--data '{"name":"string","workflow_id":36928,"workflow_params":{"set_var":{"attributes":{"vars": $postData }}}}'
NOTE the authorization token is defined in the env variables as SWWFKEY as per: https://github.com/stakwork/sphinx-tribes-frontend/issues/608
```

Where postData example is:
```
{
    "name": "Hive Ticket Builder",
    "workflow_id": 37324,
    "workflow_params": {
        "set_var": {
            "attributes": {
                "vars": {
                    "featureUUID": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                    "phaseUUID": "b07ac10b-58cc-4372-a567-0e02b2c3d480",
                    "ticketUUID": "c17ac10b-58cc-4372-a567-0e02b2c3d481",
                    "ticketName": "Implement User Authentication Flow",
                    "ticketDescription": "User Authentication System Implementation\n\nOverview:\nSecure authentication system with multiple login methods and industry-standard security.\n\nKey Requirements:\n- Email/Password auth with bcrypt hashing and verification\n- Social auth (Google OAuth2.0, Facebook)\n- Password management (reset, change, history)\n- Security features (CSRF, XSS, rate limiting)\n\nCore Features:\n1. Registration: email validation, duplicate checking\n2. Login: session management, JWT, social integration\n3. Security: password hashing, brute force protection\n\nAcceptance Criteria:\n- Email/password registration and login works\n- Social login integration functions\n- Password reset flow operates correctly\n- Security measures prevent common attacks\n\nTimeline: 16 days total\n- Setup & Auth: 8 days\n- Security & Testing: 8 days\n\nDependencies: OAuth2.0, JWT, Email service, Password hashing",
                    "productBrief": "Create a secure and user-friendly authentication system that supports both email/password and social login options while maintaining industry security standards.",
                    "featureBrief": "Develop the core authentication flow including login, registration, password reset, and social media integration (Google, Facebook) with proper error handling and validation.",
                    "examples": [
                        "# Create a route to interact with db.ticket at bounty/ticket/uuid #1976\n## Context\nWe need to create a new API endpoint to handle ticket operations (read/update/delete) as part of the bounty system. This ticket focuses on implementing the route endpoint and handler structure, which will interface with utility functions (to be implemented in a separate ticket) for database operations.\n## Task\nCreate a new REST endpoint at `/bounty/ticket/{uuid}` with a handler that processes incoming requests and routes them to the appropriate utility functions.\n## Outcome\nA functioning API endpoint that can receive and validate requests for ticket operations, with proper request parsing and error handling, ready to be connected to utility functions.\n## Design\n### 1. Request/Response Objects\n```go\n// Request structure\n\n// Response structure\n\n### 2. Handler Function\n```go\n\n### 3. Action Handler Functions\n```go\n\n### 4. Response Helper Functions\n```go\n\n## Acceptance Criteria\n- [ ] Endpoint `/bounty/ticket/{uuid}` is properly registered in the router\n- [ ] Handler correctly parses incoming requests and validates the action type\n- [ ] UUID validation is implemented\n- [ ] Response helper functions properly format JSON responses\n- [ ] Error handling is implemented for request parsing\n- [ ] Handler functions are prepared to integrate with utility functions\n",
                        "# Create route /features/uuid/phase/uuid/tickets #1982\n\nThis endpoint will be used to return the full list of ticket UUIDS for a given feature and phase uuid. \n\nAdd a route to features.go at /features/uuid/phase/uuid/tickets\n\n## Context\nWe need to create a new endpoint that returns all ticket UUIDs associated with a specific feature and phase. This endpoint will be used to fetch the complete list of tickets for a given phase within a feature.\n## Task\nAdd a new route to features.go that handles GET requests for retrieving all tickets associated with a feature and phase UUID combination.\n## Outcome\nA functioning route that accepts feature UUID and phase UUID parameters and returns the associated ticket UUIDs.\n## Design\n### Route Definition\nIn features.go:\n```go\n\n## Acceptance Criteria\n- [ ] Route `/features/{featureUUID}/phase/{phaseUUID}/tickets` is registered\n- [ ] Route is accessible via GET method\n- [ ] Route parameters are properly defined:\n  - `featureUUID`: Feature identifier\n  - `phaseUUID`: Phase identifier\n- [ ] Route is mapped to the correct handler function\n- [ ] Route follows existing project patterns for URL structure\n",
                        "# Create handler GetTickets (ByPhaseUUID) #1983\n\n## Context\nThis handler will interact with a utility function \"GetTicketsByPhase\" (https://github.com/stakwork/sphinx-tribes/issues/1984) to return an array of ticket objects for a given Phase UUID. This can be utilised to load up the ticket plan for a specific phase. \n\n## Task\nCreate a handler function that retrieves ticket UUIDs using GetTicketsByPhase based on feature UUID and phase UUID parameters.\n## Outcome\nA simplified handler that delegates database operations to the utility function.\n## Design\n```go\n\n## Acceptance Criteria\n- [ ] Handler successfully uses GetTicketsByPhase utility function\n- [ ] UUID validation in place\n- [ ] HTTP status codes are correctly set:\n  - 200: Successful retrieval\n  - 400: Invalid UUID\n  - 500: Database/Server errors\n- [ ] Response headers are properly set\n"
                    ],
                    "webhook_url": "https://<domain>/bounty/ticket/review/ "
                }
            }
        }
    }
}
```

This will send information to Stakwork. 

## Task
- Create a handler function `PostTicketDataToWorkflow` to process incoming ticket data.
- Establish the workflow object structure based on the provided input and output specifications.
- Utilize utility functions `getProductBrief` and `getFeatureBrief` to populate the workflow object (stub these functions initially).
- Implement the logic to send the prepared workflow object to the Stakwork API using a CURL request.
- Ensure proper error handling and logging for the data transmission process.

## Outcome
A functioning handler that processes ticket data and sends it to the workflow system, with the ability to handle errors and log transmission details.

## Acceptance Criteria
- [ ] Handler `PostTicketDataToWorkflow` is implemented and processes ticket data correctly.
- [ ] Workflow object is correctly structured and populated with input data.
- [ ] Utility functions `getProductBrief` and `getFeatureBrief` are stubbed and return default values.
- [ ] Data is successfully sent to the Stakwork API using a CURL request.
- [ ] Proper error handling and logging are implemented.
- [ ] The handler is tested and verified for correct functionality.

**Comment by saithsab877** [comment]
@humansinstitute, Please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute could you please assign me

**Comment by aliraza556** [comment]
@humansinstitute, Please assign me?
