### ISSUE TITLE
Implement TicketMessage Structure for WebSocket Communication in Back End

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2057]
# Ticket Name: Implement `TicketMessage` Struct for WebSocket Communication Back End

## Context
- **Problem**: The current system lacks a standardized way to process and pass messages via the WebSocket connection.
- **Need**: A structured data format is required to ensure consistent message handling and processing.
- **Background**: The `Tickets` struct already exists and will be referenced in the new `TicketMessage` struct.

## Task
1. Define a new `TicketMessage` struct in the backend codebase.

## Outcome
A new `TicketMessage` struct will be created, named correctly and available for use correctly inside the sphinx tribes back end to support upcoming websocket functionality.

## Design
- **Struct Definition**:
  - `BroadcastType`: Defines whether the message is a "pool" or "direct" broadcast.
  - `SourceSessionID`: Identifies the originating session.
  - `Message`: Contains the main message content.
  - `Action`: Specifies the action type, either "process" or "message".
  - `TicketDetails`: Utilizes the existing `Tickets` struct.

## Example Code
```go
type TicketMessage struct {
    BroadcastType   string      `json:"broadcastType"`
    SourceSessionID string      `json:"sourceSessionID"`
    Message         string      `json:"message"`
    Action          string      `json:"action"`
    TicketDetails   Tickets     `json:"ticketDetails"`
}

// Example function to handle WebSocket messages
func handleWebSocketMessage(msg TicketMessage) error {
    // Process message based on Action
    switch msg.Action {
    case "process":
        // Code to process the message
    case "message":
        // Code to handle message content
    default:
        return errors.New("unknown action type")
    }
    return nil
}
```

## Acceptance Criteria
- [ ] `TicketMessage` struct is defined and documented.
- [ ] Names and fields are correct as specified.
- [ ] Integration with existing `Tickets` struct is correct and tested
