### ISSUE TITLE
Update unmarshalling on the the UpdateTicket Handler to correctly receive an ticket request object

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2080]
File: https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L63

We are going to adjust the update functionality in the front end to pass a new object for ticketRequest. 

Instead of passing a Ticket interface directly we will pass an object with additional metadata.

```
{
    "metadata": {
        "source": "websocket",
        "id": "ws-12345"
    },
    "ticket": {
        "name": "Example Ticket",
        "feature_uuid": "...",
        "phase_uuid": "...",
        // ... other ticket fields
    }
}
```

These changes below will be to allow the handler to un-marshall the data correctly and continue operation 

```
func (th *ticketHandler) UpdateTicket(w http.ResponseWriter, r *http.Request) {
    // ... existing auth and UUID validation code ...

    body, err := io.ReadAll(r.Body)
    if err != nil {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(map[string]string{"error": "Error reading request body"})
        return
    }
    defer r.Body.Close()

    // Try to unmarshal as new format first
    var updateRequest UpdateTicketRequest
    if err := json.Unmarshal(body, &updateRequest); err != nil {
        // If that fails, try old format
        var ticket db.Tickets
        if err := json.Unmarshal(body, &ticket); err != nil {
            w.WriteHeader(http.StatusBadRequest)
            json.NewEncoder(w).Encode(map[string]string{"error": "Error parsing request body"})
            return
        }
        // Use old format ticket directly
        updateRequest.Ticket = &ticket
    }

    // If we got the new format but no ticket data, that's an error
    if updateRequest.Ticket == nil {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(map[string]string{"error": "Ticket data is required"})
        return
    }

    updateRequest.Ticket.UUID = ticketUUID
    if updateRequest.Ticket.Status != "" && !db.IsValidTicketStatus(updateRequest.Ticket.Status) {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(map[string]string{"error": "Invalid ticket status"})
        return
    }

    updatedTicket, err := th.db.CreateOrEditTicket(updateRequest.Ticket)
    // ... rest of the handler remains the same ...
}
```

## Task

- Review the design and raise questions where appropriate via Sphinx
- Update Handler and Test locally to ensure current functionality remains for Ticket updates on Phase Planner

## Acceptance Criteria

- [ ] New UpdateTicketRequest struct must be defined with:
    - Metadata field containing source and id e.g. {source: websocket, id: 1268493726904ur0439idfs}
    - Ticket field containing the existing ticket structure
- [ ] Handler successfully unmarshal both new and legacy request formats -> provide loom
- [ ] Preserve existing logic to update a ticket on each request type

**Comment by MahtabBukhari** [comment]
f

**Comment by saithsab877** [comment]
@humansinstitute Please assign me?
