### ISSUE TITLE
Update unmarshalling on endpoint `/boutnies/ticket/review/send`  to receive a ticket request object

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2081]
Based on the implementation of https://github.com/stakwork/sphinx-tribes/issues/2081

Please update the unmarshalling of ticket details in https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L161

```
{
    "metadata": {
        "source": "websocket",
        "id": "ws-12345"
    },
    "ticket": {
        "name": "Example Ticket",
        "feature_uuid": "...",
        "phase_uuid": "...",
        // ... other ticket fields
    }
}
```

To provide the same functionality of responding correctly press of `ticket builder` on the `phase planner` page to post details to StakWork Workflow. 

We will also make one additional Change to the Stakwork Call: https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L261C1-L283C3

To add the websocketID to the call example: 

```
    "featureBrief":      featureBrief,
    "examples":          "",
    "sourceWebsocket": ticketRequest.metadata.id,      // new line from the ticket request. 
    "webhook_url":       webhookURL,
```

## Task

- Review the design and raise questions where appropriate via Sphinx
- Update Handler and Test locally to ensure current functionality remains for the Phase Planner

## Acceptance Criteria

- [ ] New UpdateTicketRequest struct must be defined with:
    - Metadata field containing source and id e.g. {source: websocket, id: 1268493726904ur0439idfs}
    - Ticket field containing the existing ticket structure
- [ ] Handler successfully unmarshal both new and legacy request formats -> provide loom
- [ ] Preserve existing logic to update a ticket on each request type

**Comment by MahtabBukhari** [comment]
a

**Comment by MahtabBukhari** [comment]
as
