### ISSUE TITLE
Update `updateTicket` handler to post to websocket with channelID on successful update operation

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2086]
## Task: 
- Create a`Ticket Message` object and call `sendTicketMessage`
- Implement a utility function `sendTicketMessage` - to post a `Ticket Message` to the session ID in the message.
- On a successful update of a ticket, post an update message on the websocket. 

## Design

- In File: https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L111C2-L124C42

### sendTicketMessage Function

Logic:
```
If BroadcastType == direct send TicketMessage to websocket where sessionID = updateRequest.metadata.id
if BroadcastType == pool return - no action. // Stub this out.
```

### Message:

```
ticket_message =
{
    broadcastType: "direct",
    sourceSessionID: updateRequest.metadata.id,
    message: `Hive, has successfully updated your ticket ${updateRequest.ticket.ticketName}`,
    action: "message",        // set to message
    ticketDetails: {               // From the ticket in the original message
        featureUUID: "chjkdhu893u0qu82908394j",
        phaseUUID: "chjkdhu893u0qu09890832",
        ticketUUID: "11111-22222-33333-44444-555555",
        ticketDescription: "I'm a new ticket description"
    }
    
}
```

Websocket ID from:
- See changes in: https://github.com/stakwork/sphinx-tribes/issues/2080
- Websocket ID is available in: updateRequest.metadata.id

### Acceptance Criteria

- [ ] Message object contains all required fields (broadcastType, sourceSessionID, message, action, ticketDetails)
- [ ] sendTicketMessage function sends to correct websocket when broadcastType="direct"
- [ ] sendTicketMessage function does nothing when broadcastType="pool"
- [ ] Websocket message successfully delivered to session matching updateRequest.metadata.id
- [ ] Error handling for failed message delivery and invalid websocket connections

**Comment by aliraza556** [comment]
@humansinstitute Please assign me

**Comment by humansinstitute** [comment]
Join and post in this Sphinx Tribe for assignments:

sphinx.chat://?action=tribeV2&pubkey=0306abbf1523b90303a0b65ca3d4e1359f5079348dc4ee33625d030613875b9f47&host=tribes.v2.sphinx.chat

No Github requests / tags will be monitored.
