### ISSUE TITLE
Update `postToStakwork` handler to post to websocket with channelID on successful POST operation

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2087]
## Task: 
- Create a`Ticket Message` object and call `sendTicketMessage`
- Reuse utility function `sendTicketMessage` -from https://github.com/stakwork/sphinx-tribes/issues/2086
- On a successful POST of data to Stakwork, post an update message on the websocket. 

## Design

- In File: https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L161

### Message:

```
ticket_message =
{
    broadcastType: "direct",
    sourceSessionID: updateRequest.metadata.id,
    message: `I have your updates and Im rewriting ticket ${updateRequest.ticket.ticketName} now`,
    action: "message",        // set to message
    ticketDetails: {               // From the ticket in the original message
        featureUUID: "chjkdhu893u0qu82908394j",
        phaseUUID: "chjkdhu893u0qu09890832",
        ticketUUID: "11111-22222-33333-44444-555555",
        ticketDescription: "I'm a new ticket description"
    }
    
}
```

Websocket ID from:
- See changes in: https://github.com/stakwork/sphinx-tribes/issues/2080
- Websocket ID is available in: updateRequest.metadata.id

### Acceptance Criteria

- [ ] Message object contains all required fields (broadcastType, sourceSessionID, message, action, ticketDetails)
- [ ] Correctly calls existing sendTicketMessage
- [ ] Websocket message successfully delivered to session matching updateRequest.metadata.id
- [ ] Error handling for failed message delivery and invalid websocket connections

**Comment by aliraza556** [comment]
@humansinstitute Please assign me

**Comment by Shoaibdev7** [comment]
@humansinstitute assign ?

**Comment by MahtabBukhari** [comment]
@humansinstitute please assign?
