### ISSUE TITLE
Add Ticket Link component to `Ticket Editor`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2120]
Update add a link to the ticket editor component.

https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/components/common/TicketEditor/TicketEditor.tsx

## Task

- Add a temporary state to Phase Planner view and display the stakwork link for a specific ticket UUIDs. 
- Add a temporary SWWF link button next to the Update button
- This will be empty on load for a ticket UUID and if so this button shouldn't be displayed
- When a websocket updates the state display the button with the correct link

## Design

1. First, add the state to PhasePlannerView:
File: https://github.com/stakwork/sphinx-tribes-frontend/blob/master/src/people/widgetViews/PhasePlannerView.tsx

```tsx
const PhasePlannerView: React.FC = () => {
  // ... existing state ...
  const [swwfLinks, setSwwfLinks] = useState<Record<string, string>>({});
```

2. Update the websocket message handler in PhasePlannerView:

```tsx
socket.onmessage = async (event: MessageEvent) => {
  try {
    const data = JSON.parse(event.data);

    if (data.msg === SOCKET_MSG.user_connect) {
      const sessionId = data.body;
      setWebsocketSessionId(sessionId);
      console.log(`Websocket Session ID: ${sessionId}`);
      return;
    }

    // Handle SWWF link updates
    if (data.ticket_uuid && data.swwf_id) {
      setSwwfLinks(prev => ({
        ...prev,
        [data.ticket_uuid]: data.swwf_id
      }));
    }

    const ticketMessage = data as TicketMessage;
    // ... rest of your existing message handling ...
  } catch (error) {
    console.error('Error processing websocket message:', error);
  }
};
```

3. Modify the TicketEditor props interface:
```tsx
interface TicketEditorProps {
  ticketData: {
    uuid: string;
    feature_uuid: string;
    phase_uuid: string;
    name: string;
    sequence: number;
    dependency: string[];
    description: string;
    status: string;
    version: number;
    number: number;
  };
  websocketSessionId: string;
  swwfLink?: string;  // Add this new prop
}
```

4. Update how you render TicketEditor in PhasePlannerView:
```tsx
{ticketData.map((ticketData: TicketData) => (
  <TicketEditor
    key={ticketData.uuid}
    ticketData={ticketData}
    websocketSessionId={websocketSessionId}
    swwfLink={swwfLinks[ticketData.uuid]}
  />
))}
```

5. Simplify the TicketEditor component by removing its internal SWWF state and websocket handling:
```tsx
const TicketEditor = ({ ticketData, websocketSessionId, swwfLink }: TicketEditorProps) => {
  const [name, setName] = useState(ticketData.name || 'Ticket');
  const [description, setDescription] = useState(ticketData.description || '');
  const [toasts, setToasts] = useState<Toast[]>([]);
  const { main } = useStores();

  // Remove the websocket useEffect...

  // In the return statement, update the button rendering:
  <TicketButtonGroup>
    <ActionButton color="primary" onClick={handleUpdate} data-testid="story-input-update-btn">
      Update
    </ActionButton>
    {swwfLink && (
      <ActionButton 
        as="a" 
        href={`https://jobs.stakwork.com/admin/projects/${swwfLink}`}
        target="_blank"
        rel="noopener noreferrer"
        style={{ textDecoration: 'none' }}
      >
        SW Run: {swwfLink}
      </ActionButton>
    )}
    <ActionButton
      color="#49C998"
      onClick={handleTicketBuilder}
      data-testid="story-generate-btn"
    >
      Ticket Builder
    </ActionButton>
  </TicketButtonGroup>
```

This approach has several benefits:
1. Single source of truth for SWWF links
2. More efficient websocket handling (one listener instead of many)
3. Cleaner ticket editor component with fewer responsibilities
4. Better state management and performance
5. Easier to add features like persisting SWWF links if needed

## Acceptance Criteria
- [ ] The `swwfLink` state is correctly initialized to `null` upon component load.
- [ ] The SWWF link button does not appear if `swwfLink` is `null`.
- [ ] When `swwfLink` is updated e.g. `73123248`, the SWWF link button appears between the Update and Ticket Builder buttons.
- [ ] The SWWF link button redirects to the correct Stakwork project URL in a new window
- [ ] UI should be consistent with the `Ticket Builder` button

**Comment by humansinstitute** [comment]
Join and post in this Sphinx Tribe for assignments:

sphinx.chat://?action=tribeV2&pubkey=0306abbf1523b90303a0b65ca3d4e1359f5079348dc4ee33625d030613875b9f47&host=tribes.v2.sphinx.chat

No Github requests / tags will be monitored.

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can i  help?

**Comment by aliraza556** [comment]
@humansinstitute please assign me?

**Comment by aliraza556** [comment]
@humansinstitute Please move frontend side.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?

**Comment by MuhammadUmer44** [comment]
Hi @humansinstitute Please assign me?

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can I help?

**Comment by MuhammadUmer44** [comment]
Hi @humansinstitute Please assign me this one?

**Comment by saithsab877** [comment]
@humansinstitute Please assign me?

**Comment by AhsanFarooqDev** [comment]
@humansinstitute i can help it's my first comment
