### ISSUE TITLE
Create endpoints in Workspace.go to manage WorkspaceCodeGraph

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2151]
# Add WorkspaceCodeGraph Endpoints and Handlers

## Description
Add endpoints and handlers to manage WorkspaceCodeGraph entities, following the existing patterns used in the workspace codebase. The endpoints will provide GET, POST, and DELETE operations for code graph management.

### 1. Add Routes in routes/workspace.go
```go
// Add inside the Group function
r.Group(func(r chi.Router) {
    // ... existing routes ...
    
    // CodeGraph routes
    r.Get("/{uuid}/codegraph", workspaceHandlers.GetCodeGraph)
    r.Post("/{uuid}/codegraph", workspaceHandlers.UpdateCodeGraph)
    r.Delete("/{uuid}/codegraph", workspaceHandlers.DeleteCodeGraph)
})
```

### 2. Add Handler Functions in handlers/workspace.go

```go
// GetCodeGraph retrieves the code graph for a workspace
func (oh *workspaceHandler) GetCodeGraph(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    pubKeyFromAuth, _ := ctx.Value(auth.ContextKey).(string)
    if pubKeyFromAuth == "" {
        fmt.Println("[workspaces] no pubkey from auth")
        w.WriteHeader(http.StatusUnauthorized)
        return
    }

    uuid := chi.URLParam(r, "uuid")
    codeGraph, err := oh.db.GetCodeGraphByUUID(uuid)
    if err != nil {
        if err.Error() == "code graph not found" {
            w.WriteHeader(http.StatusNotFound)
            json.NewEncoder(w).Encode(map[string]string{"error": "Code graph not found"})
            return
        }
        w.WriteHeader(http.StatusInternalServerError)
        json.NewEncoder(w).Encode(map[string]string{"error": fmt.Sprintf("Failed to get code graph: %v", err)})
        return
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(codeGraph)
}

// UpdateCodeGraph creates or updates a code graph for a workspace
func (oh *workspaceHandler) UpdateCodeGraph(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    pubKeyFromAuth, _ := ctx.Value(auth.ContextKey).(string)
    if pubKeyFromAuth == "" {
        fmt.Println("[workspaces] no pubkey from auth")
        w.WriteHeader(http.StatusUnauthorized)
        return
    }

    uuid := chi.URLParam(r, "uuid")
    
    var codeGraph db.WorkspaceCodeGraph
    body, err := io.ReadAll(r.Body)
    defer r.Body.Close()
    
    if err != nil {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(map[string]string{"error": "Error reading request body"})
        return
    }

    if err := json.Unmarshal(body, &codeGraph); err != nil {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(map[string]string{"error": "Error parsing request body"})
        return
    }

    // Set metadata
    now := time.Now()
    codeGraph.Updated = &now
    codeGraph.UpdatedBy = pubKeyFromAuth
    if codeGraph.Uuid == "" {
        codeGraph.Uuid = uuid
        codeGraph.Created = &now
        codeGraph.CreatedBy = pubKeyFromAuth
    }
    codeGraph.WorkspaceUuid = uuid

    updatedCodeGraph, err := oh.db.UpdateCodeGraphByUUID(codeGraph)
    if err != nil {
        w.WriteHeader(http.StatusInternalServerError)
        json.NewEncoder(w).Encode(map[string]string{"error": fmt.Sprintf("Failed to update code graph: %v", err)})
        return
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(updatedCodeGraph)
}

// DeleteCodeGraph removes a code graph from a workspace
func (oh *workspaceHandler) DeleteCodeGraph(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    pubKeyFromAuth, _ := ctx.Value(auth.ContextKey).(string)
    if pubKeyFromAuth == "" {
        fmt.Println("[workspaces] no pubkey from auth")
        w.WriteHeader(http.StatusUnauthorized)
        return
    }

    uuid := chi.URLParam(r, "uuid")
    
    err := oh.db.DeleteCodeGraphByUUID(uuid)
    if err != nil {
        if err.Error() == "code graph not found" {
            w.WriteHeader(http.StatusNotFound)
            json.NewEncoder(w).Encode(map[string]string{"error": "Code graph not found"})
            return
        }
        w.WriteHeader(http.StatusInternalServerError)
        json.NewEncoder(w).Encode(map[string]string{"error": fmt.Sprintf("Failed to delete code graph: %v", err)})
        return
    }

    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(map[string]string{"message": "Code graph deleted successfully"})
}
```

## Task List
1. Add the new routes to routes/workspace.go
2. Implement the three handler functions in handlers/workspace.go
3. Test the endpoints with appropriate authorization
4. Verify error handling matches existing patterns
5. Ensure proper status codes are returned
6. Test integration with the DB functions

## Acceptance Criteria
- [ ] All three endpoints are implemented and accessible
- [ ] Handler functions properly integrate with DB functions
- [ ] Authorization is properly checked
- [ ] Error handling follows existing patterns
- [ ] Status codes match REST conventions
- [ ] Response format matches existing endpoints

**Comment by saithsab877** [comment]
,

**Comment by MuhammadUmer44** [comment]
l

**Comment by Shoaibdev7** [comment]
@humansinstitute I can help?
