### ISSUE TITLE
Update /review/send to Include Code Graph URL in Stakwork Response

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2152]
## Description
Modify the `/review/send` endpoint to retrieve the WorkspaceCodeGraph URL and include it in the Stakwork payload response. The URL should be retrieved based on the workspace UUID associated with the feature.

### 1. Modify PostTicketDataToStakwork Function
Add code graph URL retrieval and include it in the Stakwork payload:

```go
// In PostTicketDataToStakwork handler
var (
    productBrief, featureBrief, codeGraphURL string
    feature                    db.WorkspaceFeatures
)

if ticket.FeatureUUID != "" {
    feature = th.db.GetFeatureByUuid(ticket.FeatureUUID)
    if feature.Uuid == "" {
        // ... existing error handling ...
    }

    // Get code graph URL for the workspace
    if feature.WorkspaceUuid != "" {
        codeGraph, err := th.db.GetCodeGraphByWorkspaceUUID(feature.WorkspaceUuid)
        if err == nil {
            codeGraphURL = codeGraph.Url
        }
        // Note: We don't error if code graph isn't found - it's optional
    }

    // ... existing feature brief and product brief retrieval ...
}

// Update stakwork payload to include codeGraph
stakworkPayload := map[string]interface{}{
    "name":        "Hive Ticket Builder",
    "workflow_id": 37324,
    "workflow_params": map[string]interface{}{
        "set_var": map[string]interface{}{
            "attributes": map[string]interface{}{
                "vars": map[string]interface{}{
                    // ... existing fields ...
                    "codeGraph": codeGraphURL,  // Add this line
                },
            },
        },
    },
}
```

## Task List
1. Update variable declarations in PostTicketDataToStakwork
2. Add code graph retrieval logic after feature validation
3. Modify Stakwork payload to include code graph URL
4. Test endpoint with and without code graph present
5. Update unit tests

## Acceptance Criteria
- [ ] Code graph URL is retrieved when available
- [ ] URL is correctly included in Stakwork payload
- [ ] Empty string is sent when no code graph exists
- [ ] Existing functionality remains unchanged
- [ ] Error handling follows existing patterns

**Comment by MuhammadUmer44** [comment]
,

**Comment by MahtabBukhari** [comment]
f

**Comment by Shoaibdev7** [comment]
j

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can i help?
