### ISSUE TITLE
Generate Endpoints to Manage Chat History

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2154]
Add Chat Management Endpoints and Handlers

## Description
Add endpoints and handlers to manage Chat and ChatMessage entities, following existing patterns in the codebase. The endpoints will provide operations for chat creation, message sending, history retrieval, and response processing.

### 1. Update routes/chat.go
```go
// Add routes for chat management
func ChatRoutes() chi.Router {
    r := chi.NewRouter()
    chatHandler := handlers.NewChatHandler(http.DefaultClient, db.DB)

    // Public endpoint
    r.Post("/response", chatHandler.ProcessChatResponse)

    // Protected routes
    r.Group(func(r chi.Router) {
        r.Use(auth.PubKeyContext)
        r.Post("/", chatHandler.CreateChat)
        r.Post("/send", chatHandler.SendMessage)
        r.Get("/history/{uuid}", chatHandler.GetChatHistory)
    })

    return r
}
```

### 2. Add Handler Functions in handlers/chat.go
- Implement `NewChatHandler` constructor
- Add `ChatResponse` struct for consistent response formatting
- Add handler functions:
  - `CreateChat`: Create new chat sessions
  - `SendMessage`: Send messages to stakwork (stub out)
  - `GetChatHistory`: Retrieve chat history
  - `ProcessChatResponse`: Handle Stakwork responses (stub out)

### 3. Use DB Interface in db/chat.go

```go
type ChatDB interface {
    AddChat(chat *Chat) (Chat, error)
    GetChatByChatID(chatID string) (Chat, error)
    AddChatMessage(message *ChatMessage) (ChatMessage, error)
    GetChatMessagesForChatID(chatID string) ([]ChatMessage, error)
}
```

## Required Features
- Chat creation with workspace association
- Message sending with Stakwork integration
- Chat history retrieval
- Stakwork response processing
- WebSocket notifications for real-time updates
- Proper error handling and status codes
- Authorization checks

## Task List
1. Update database functions in db/chat.go
2. Create chat routes in routes/chat.go
3. Implement handler functions in handlers/chat.go
4. Add proper error handling and response formatting
5. Implement Stakwork integration
6. Add WebSocket notification support
7. Test all endpoints with authorization

## Acceptance Criteria
- [ ] All endpoints are implemented and accessible
- [ ] Handler functions properly integrate with DB functions
- [ ] Authorization is properly checked
- [ ] Error handling follows existing patterns
- [ ] Status codes match REST conventions
- [ ] Stakwork integration is stubbed out 

### POST /chat
Create a new chat session
```json
Request:
{
    "workspaceId": "string",
    "title": "string"
}

Response:
{
    "success": true,
    "message": "Chat created successfully",
    "data": {
        "id": "string",
        "workspaceId": "string",
        "title": "string",
        "createdAt": "timestamp",
        "updatedAt": "timestamp"
    }
}
```

### POST /chat/send
Send a message in an existing chat
```json
Request:
{
    "chatId": "string",
    "message": "string",
    "contextTags": [
        {
            "type": "string",
            "id": "string"
        }
    ]
}

Response:
{
    "success": true,
    "message": "Message sent successfully",
    "data": {
        "id": "string",
        "chatId": "string",
        "message": "string",
        "role": "user",
        "timestamp": "timestamp",
        "status": "sending"
    }
}
```

### GET /chat/history/{uuid}
Retrieve chat history
```json
Response:
{
    "success": true,
    "data": [
        {
            "id": "string",
            "chatId": "string",
            "message": "string",
            "role": "string",
            "timestamp": "timestamp",
            "contextTags": [],
            "status": "string",
            "source": "string"
        }
    ]
}
```

### POST /chat/response
Process Stakwork responses (public endpoint)
```json
Request:
{
    "chatId": "string",
    "message": "string"
}

Response:
200 OK
```

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can i help?

**Comment by Shoaibdev7** [comment]
@humansinstitute Please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute assign
