### ISSUE TITLE
Update the Hive Chat Endpoints to Correctly Process New Chats

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2163]
## Overview
Update the chat handler's SendMessage function to integrate with Stakwork workflow and maintain message history synchronization.

### Data Structures
```go
// Add new types to support the enhanced functionality
type ChatHistoryResponse struct {
    Messages []db.ChatMessage `json:"messages"`
}

type StakworkChatPayload struct {
    Name           string                 `json:"name"`
    WorkflowID     int                   `json:"workflow_id"`
    WorkflowParams map[string]interface{} `json:"workflow_params"`
}

type ChatWebhookResponse struct {
    Success bool           `json:"success"`
    Message string        `json:"message"`
    ChatID  string        `json:"chat_id"`
    History []ChatMessage `json:"history"`
}
```

### Implementation Steps

1. **Update SendMessage Handler**
```go
func (ch *ChatHandler) SendMessage(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    
    // Parse request
    var request struct {
        ChatID            string     `json:"chatId"`
        Message           string     `json:"message"`
        ContextTags       []ContextTag `json:"contextTags"`
        SourceWebsocketID string     `json:"sourceWebsocketId"`
    }
    
    if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
        w.WriteHeader(http.StatusBadRequest)
        json.NewEncoder(w).Encode(ChatResponse{
            Success: false,
            Message: "Invalid request body",
        })
        return
    }
    
    // 1. Fetch last 20 messages from history
history, err := ch.db.GetChatMessagesForChatID(request.ChatID)
if err != nil {
    w.WriteHeader(http.StatusInternalServerError)
    json.NewEncoder(w).Encode(ChatResponse{
        Success: false,
        Message: fmt.Sprintf("Failed to fetch chat history: %v", err),
    })
    return
}

// Get last 20 messages (they're already ordered by timestamp ASC)
start := 0
if len(history) > 20 {
    start = len(history) - 20
}
recentHistory := history[start:]

// Map to array of role-based message objects
messageHistory := make([]map[string]string, len(recentHistory))
for i, msg := range recentHistory {
    messageHistory[i] = map[string]string{
        msg.Role: msg.Message,
    }
}
    
    // 2. Create and save new message
    message := &db.ChatMessage{
        ID:        xid.New().String(),
        ChatID:    request.ChatID,
        Message:   request.Message,
        Role:      "user",
        Timestamp: time.Now(),
        Status:    "sending",
        Source:    "user",
    }
    
    createdMessage, err := ch.db.AddChatMessage(message)
    if err != nil {
        w.WriteHeader(http.StatusInternalServerError)
        json.NewEncoder(w).Encode(ChatResponse{
            Success: false,
            Message: fmt.Sprintf("Failed to save message: %v", err),
        })
        return
    }
    
    // 3. Send to Stakwork
    stakworkPayload := StakworkChatPayload{
        Name:       "Hive Chat Processor",
        WorkflowID: 38842, // actual workflow ID
        WorkflowParams: map[string]interface{}{
            "set_var": map[string]interface{}{
                "attributes": map[string]interface{}{
                    "vars": map[string]interface{}{
                        "chatId":            request.ChatID,
                        "messageId":         createdMessage.ID,
                        "message":           request.Message,
                    "history":           messageHistory, // Array of {role: message} objects
                       "contextTags":    "This is a project with Typescript frontend and Go Backend",  // hard code for now will update next phase
                        "sourceWebsocketId": request.SourceWebsocketID,
                        "webhook_url":       fmt.Sprintf("%s/hivechat/process", os.Getenv("HOST")),
                    },
                },
            },
        },
    }
    
    // Send to Stakwork
    if err := ch.sendToStakwork(stakworkPayload); err != nil {
        // Update message status to error
        createdMessage.Status = "error"
        ch.db.UpdateChatMessage(createdMessage)
        
        w.WriteHeader(http.StatusInternalServerError)
        json.NewEncoder(w).Encode(ChatResponse{
            Success: false,
            Message: fmt.Sprintf("Failed to process message: %v", err),
        })
        return
    }
    
    // 4. Send websocket notification
    wsMessage := websocket.TicketMessage{
        BroadcastType:   "direct",
        SourceSessionID: request.SourceWebsocketID,
        Message:         "Message sent",
        Action:          "process",
        ChatMessage:     createdMessage,
    }
    
    if err := websocket.WebsocketPool.SendTicketMessage(wsMessage); err != nil {
        log.Printf("Failed to send websocket message: %v", err)
    }
    
    // Return success response
    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(ChatResponse{
        Success: true,
        Message: "Message sent successfully",
        Data:    createdMessage,
    })
}

// Helper function to send payload to Stakwork
func (ch *ChatHandler) sendToStakwork(payload StakworkChatPayload) error {
    payloadJSON, err := json.Marshal(payload)
    if err != nil {
        return fmt.Errorf("error marshaling payload: %v", err)
    }
    
    req, err := http.NewRequest(
        http.MethodPost,
        "https://api.stakwork.com/api/v1/projects",
        bytes.NewBuffer(payloadJSON),
    )
    if err != nil {
        return fmt.Errorf("error creating request: %v", err)
    }
    
    apiKey := os.Getenv("SWWFKEY")
    if apiKey == "" {
        return fmt.Errorf("SWWFKEY environment variable not set")
    }
    
    req.Header.Set("Authorization", "Token token="+apiKey)
    req.Header.Set("Content-Type", "application/json")
    
    resp, err := ch.httpClient.Do(req)
    if err != nil {
        return fmt.Errorf("error sending request: %v", err)
    }
    defer resp.Body.Close()
    
    if resp.StatusCode != http.StatusOK {
        body, _ := io.ReadAll(resp.Body)
        return fmt.Errorf("stakwork API error: %s", string(body))
    }
    
    return nil
}
```

## Acceptance Criteria

- [ ] Stakwork workflows correctly triggered via endpoint (confirm on staging)
- [ ] Endpoint correctly integrates with front end
- [ ] Message history correctly updated
- [ ] Websocket messages returned to Front end for auto updates

**Comment by humansinstitute** [comment]
Join and post in this Sphinx Tribe for assignments:

sphinx.chat://?action=tribeV2&pubkey=0306abbf1523b90303a0b65ca3d4e1359f5079348dc4ee33625d030613875b9f47&host=tribes.v2.sphinx.chat

No Github requests / tags will be monitored.

There is no policy to award work to who tagged first.

**Comment by Shoaibdev7** [comment]
H

**Comment by aliraza556** [comment]
@humansinstitute assigne me

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can I help

**Comment by MahtabBukhari** [comment]
@humansinstitute assign me

**Comment by MuhammadUmer44** [comment]
@humansinstitute assign me

**Comment by MahtabBukhari** [comment]
@humansinstitute https://community.sphinx.chat/p/cs6elnatu2rsh7eq5hk0/assigned/2951/10

**Comment by humansinstitute** [comment]
> [@humansinstitute](https://github.com/humansinstitute) https://community.sphinx.chat/p/cs6elnatu2rsh7eq5hk0/assigned/2951/10

This is actually quite useful to make payment quicker :)
