### ISSUE TITLE
Logging Project Feature Tracking

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2168]
### Goal
The goal is to create more verbose logging in sphinx-tribes such that it give enough information to LLM to effectivly create solutions for both Internal Server Errors and also for Logical Errors in the sphinx-tribes codebase

#### Phase 1 (Middleware for stacktrace to Jarvis)
- [ ] Env var for jarvis url `JARVIS_URL`
- [ ] Env var for jarvis token `JARVIS_TOKEN`
- [ ] Create middleware function for internal server error
  - [ ] Create function to listen for 500 errors
  - [ ] Get stacktrace in 500 error
  - [ ] Format stacktrace to fit edge_list body
  - [ ] Create Post request to jarvis node/edge/bulk

Stretch Goal
- [ ] modify jarvis to accept final variable state
  - [ ] send the final variable state to jarvis

#### Phase 2 (Debugger for verbose logging)
- [ ] Figure out which debugger logger we should use
- [ ] Create ENV var for `LOG_LEVEL`
- [ ] Create logger middleware
  - [ ] Print on each request only if `LOG_LEVEL=Machine`
  - [ ] Similar to jarvis log a unique uuid for each request
  - [ ] Log each line for the whole trace for each request
  - [ ] Log the diff in variables from the previous line

Stretch Goal
- [ ] Save the logs for 24 hours somewhere

#### Phase 3 (Connect debugger logs to middleware)
- [ ] Figure out how to read from the exisitng logs from middleware when 500 Error
- [ ] At this point we need to rethink how jarvis proccess the request instead of just a stacktrace

#### Phase 4 (Logical Errors)
- [ ] Create new header that is called `X_JARVIS_QUESTION`
- [ ] Modify logger middleware to send to jarvis if `X_JARIVS_QUESTION` is not None and include the stacktrace even if successful
- [ ] Modify Jarvis /node/edge/bulk to have an optional question param

----

TODO:
Create issues for each one of these tasks and also refine these steps to solve this problem
