### ISSUE TITLE
Bounties dashboard for users and organisations

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#612]
# Goal

To create a dashboard that allows users/organizations to create bounties and get reports and statistics of bounties created.

## Features

- Users should be able to create an organization
- They can give access to other users to have access to their created organizations 
- A user control access should be in place, not all users should have access to every feature.
- Users should be able to create, update, delete, and re-assign bounties
- Users should be able to view bounties created by only their organization or bounties accessible to the general public.
- Users should be able to view a leaderboard for their organization's bounties
- Users should be able to see the total number of satoshis they have spent on completed bounties, see the total of completed and  not completed bounties
- The bounty page should have a list of organizations, users should be able to click and see the list of not completed or assigned bounties and also see the organization's bounty leaderboard.

**Comment by kevkevinpal** [comment]
yes I think this is good in addition
* organization owners should be able to delegate an amount of satoshis a member of the org can spend on bounties

**Comment by kevkevinpal** [comment]
we might just need to narrow down the specifics like 
where does all this data go? 
is it in a new table? 
are we adding fields to an existing table?
how can we code this with unit and integration testing to insure things don't break.
what will the UI look like ( if you can hand draw a picture that would be helpful )

**Comment by elraphty** [comment]
# Tribes Organisations Multi-tenancy App

- Organisations will be distinguished using a UUID saved on the people's table
- There will be 2 categories of users (1) user (2) Organization
- The creator of the organization will be the organization admin and will have access to every Sphinx Tribes functionality 
- Organizations will be able to add users' public keys to a new organization users table, the users on the table will be able to have access to the organization tickets, post and delete dependent on the access given to them.
- There will be a newly created table access table, which will house all the functionalities that can be performed on Sphinx Tribes
- There will be a new organization access table that will determine the access given to each organization user.
- A new budget table will be created to keep an amount to be paid for tickets, organizations can deposit some amount of Sats which will be reflected on the budget table, and organization users can pay for tickets with the sats deposited in the budget table
- The will be a table for the history of ticket payments will keep records of all the ticket payments made
- Organizations can also decide to pay directly to the ticket assignee without using the budget functionality, an invoice will be created and when successfully paid, it will be added to the transaction history table.

**Comment by kevkevinpal** [comment]
its looking good if you could create some structs for the tables similar to what is in db/structs.go that would be helpful

seems like you’re proposing a few new tables
1). table access table
2). organization access table
3). budget table
4). history of ticket payments table

and also an addition to the people table with an org field with a uuid

instead of modifying the people table we can just have a uuid on the org table specifying the owners and members of the org

**Comment by elraphty** [comment]
@kevkevinpal, and @Evanfeenstra, these are the Database structs for the organization tables

```type Organization struct {
	UUID        string     `json:"uuid"`
	Name        string     `json:"name"`
	OwnerPubKey string     `json:"owner_pubkey"`
	Img         string     `json:"img"`
	Created     *time.Time `json:"created"`
	Updated     *time.Time `json:"updated"`
	Show        bool       `json:"show"`
}

type OrganizationUsers struct {
	OwnerPubKey  string     `json:"owner_pubkey"`
	Organization string     `json:"organization"`
	Created      *time.Time `json:"created"`
	Updated      *time.Time `json:"updated"`
}

type BountyRoles struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

type UserRoles struct {
	Role         string     `json:"role"`
	OwnerPubKey  string     `json:"owner_pubkey"`
	Organization string     `json:"organization"`
	Created      *time.Time `json:"created"`
	Updated      *time.Time `json:"updated"`
}

type BountyBudget struct {
	Organization string     `json:"organization"`
	TotalBudget  uint       `json:"total_budget"`
	Created      *time.Time `json:"created"`
	Updated      *time.Time `json:"updated"`
}

type BudgetHistory struct {
	Organization string     `json:"organization"`
	Amount       uint       `json:"amount"`
	SenderPubKey string     `json:"sender_pubkey"`
	Created      *time.Time `json:"created"`
	Updated      *time.Time `json:"updated"`
}

type PaymentHistory struct {
	Organization   string     `json:"organization"`
	SenderPubKey   string     `json:"sender_pubkey"`
	ReceiverPubKey string     `json:"receiver_pubkey"`
	Amount         uint       `json:"amount"`
	BountyId       uint       `json:"id"`
	Created        *time.Time `json:"created"`
}```

**Comment by ecurrencyhodler** [comment]
This organization is a massive feature. Let's break it down into smaller pieces. Below are the pieces Raph spec'd out and their corresponding issue #'s. 
- [ ] Users should be able to create an organization (#612)
- [ ] They can give access to other users to have access to their created organizations (#612)
- [ ] A user control access should be in place, not all users should have access to every feature. (TBD)
- [ ] Users should be able to create, update, delete, and re-assign bounties. (#650, #659)
- [ ] Users should be able to view bounties created by only their organization or bounties accessible to the general public. (#612)
- [ ] ~Users should be able to view a leaderboard for their organization's bounties~ I don't think we need this for the beta launch.
- [ ] Users should be able to see the total number of satoshis they have spent on completed bounties, see the total of completed and not completed bounties (TBD)
- [ ] The bounty page should have a list of organizations, users should be able to click and see the list of not completed or assigned bounties and also see the organization's bounty leaderboard. (TBD)

**Comment by ecurrencyhodler** [comment]
How that we have new UI in, I'm going to close this issue out as all other tasks have been broken down.
